version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    labels:
      - "Type: CI"
      - "Type: Dependencies"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
    labels:
      - "Type: Dependencies"
    groups:
      types:
        patterns:
          - "@types/*"
      eslint:
        patterns:
          - "*eslint*"
    ignore:
      - dependency-name: "@types/node" # Node.jsのバージョンはこちらでLTSを前提にコントロールしたいため。
        update-types:
          - "version-update:semver-major"
